name: CI - Plataforma Anime

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: ğŸ“¦ Checkout do cÃ³digo
        uses: actions/checkout@v4

      - name: âš™ï¸ Setup pnpm
        uses: pnpm/action-setup@v4

      - name: ğŸŸ¢ Setup Node.js 22 com cache pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml # garante que o cache sÃ³ renove quando o lock mudar

      - name: Ativar pnpm com corepack
        run: |
          corepack enable  
          corepack install

      - name: ğŸ“¥ Instalar dependÃªncias
        run: pnpm install

      - name: âœ… Rodar testes
        run: pnpm test

      - name: ğŸ”¨ Build da aplicaÃ§Ã£o
        run: pnpm run build
